@echo off
echo [EmotionCore] Initializing Git...
git init
echo [EmotionCore] Adding files...
git add .
echo [EmotionCore] Committing...
git commit -m "Initial commit of EmotionCore framework"
echo [EmotionCore] Branching...
git branch -M main
echo [EmotionCore] Setting remote...
git remote add origin https://github.com/Chaitanyahoon/EmotionCore
echo [EmotionCore] Pushing to GitHub...
git push -u origin main
echo [EmotionCore] DONE.
pause
